# Generated by Django 4.1.7 on 2023-02-28 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('price', models.PositiveBigIntegerField()),
                ('slug', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Suplyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sypplyer_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProductInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.product')),
                ('sypplyer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.suplyer')),
            ],
        ),
    ]
