# Generated by Django 4.1.7 on 2023-03-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_productinput_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinput',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
