# Generated by Django 4.1.7 on 2023-03-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_productinput_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(default='company name', max_length=250)),
                ('tax_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='productinput',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PosSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.client')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.product')),
            ],
        ),
    ]
