# Generated by Django 4.1.7 on 2023-03-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_checkout_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinputcart',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
