# Generated by Django 4.1.7 on 2023-03-12 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_productinputcart_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinputcart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.product'),
        ),
    ]
