# Generated by Django 4.1.7 on 2023-03-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_alter_productinputcart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='Discount_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
