# Generated by Django 4.1.7 on 2023-03-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_possale_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possale',
            name='Discount_price',
            field=models.IntegerField(default=0),
        ),
    ]
