# Generated by Django 4.1.7 on 2023-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_alter_possale_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tax_number',
            field=models.IntegerField(default=300950786200003),
        ),
    ]
