# Generated by Django 4.1.7 on 2023-03-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_alter_client_tax_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='possale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.possale'),
        ),
    ]
