# Generated by Django 4.1.7 on 2023-04-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0019_remove_possale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='possale',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
