# Generated by Django 4.1.7 on 2023-04-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0020_possale_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTrasctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(default='company', max_length=250),
        ),
    ]
