# Generated by Django 4.1.7 on 2023-04-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0023_addcash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcash',
            old_name='reason',
            new_name='Reason',
        ),
        migrations.RenameField(
            model_name='addcash',
            old_name='money',
            new_name='add_money',
        ),
    ]
